### 関数

iterator

In [1]:
import torch
dataset = []
for i in range(1000):
    data = torch.randn(3,224,224)
    dataset.append(data)

In [2]:
class DataLoader:
    def __init__(self,dataset,max):
        self.dataset = dataset
        self._max = max

    def __iter__(self):
        self._count = 0
        return self
    
    def __next__(self):
        i = self._count
        if i >= self._max:
            raise StopIteration

        self._count += 1

        return self.dataset[i]

In [3]:
dataloader = DataLoader(dataset,10)
for i,data in enumerate(dataloader):
    print(data)

tensor([[[ 1.2147, -0.5298,  1.8472,  ..., -1.5453,  0.3894,  0.7934],
         [ 0.0318,  1.2768,  0.8465,  ...,  0.1768, -0.6308,  1.2081],
         [ 0.4839, -1.4650, -0.7037,  ...,  0.5944, -0.7347,  1.0029],
         ...,
         [-0.5064,  0.0343,  1.0873,  ..., -0.9595, -0.9509,  0.6189],
         [ 0.3188, -0.5073,  2.2162,  ...,  1.1340,  1.8409,  1.3584],
         [ 0.4570,  1.0990,  0.3428,  ..., -1.2273,  0.1082, -1.0004]],

        [[-0.8687, -0.5942, -0.4483,  ...,  0.2506, -0.5423, -0.6904],
         [-0.7897, -0.5409,  0.4658,  ...,  0.9778, -1.7955, -0.9498],
         [-0.5294, -0.4005,  0.2692,  ..., -0.2763,  0.1107,  1.3739],
         ...,
         [-0.9612, -0.0158,  1.1625,  ...,  1.3901,  0.8890, -2.6968],
         [ 0.0442,  1.6304,  0.2819,  ...,  0.3025,  1.6381, -0.5958],
         [-0.0768, -0.3482,  0.8340,  ...,  0.4218, -0.9875, -1.4056]],

        [[ 2.3474, -0.0548,  0.7884,  ...,  0.2892, -1.3120,  0.3573],
         [ 0.4451, -0.5570, -0.3332,  ...,  0

In [13]:
class MyClass:
    """this is my class for experiment"""
    def __init__(self):
        self.x = 0

    def __add_return__(self):
        self.x +=1
        return self.x
    
myclass = MyClass()
add_return(myclass)

NameError: name 'add_return' is not defined

In [14]:
aaa = iter([1,2,3])
next(aaa)

1

In [15]:
next(aaa)

2

In [16]:
aaa = [1,2,3]
list(map(lambda x:x*2,aaa))

[2, 4, 6]

In [17]:
MyClass.__doc__

'this is my class for experiment'

In [22]:
myfunc = lambda x:x**2
print(myfunc(3))
print(list(map(myfunc,aaa)))

9
[1, 4, 9]


In [2]:
import torch
torch.manual_seed(3)
def Dataset(list):
    for num in list:
        yield torch.randn(1)
    
for data in Dataset(range(10)):
    print(data)

tensor([0.8033])
tensor([0.1748])
tensor([0.0890])
tensor([-0.6137])
tensor([0.0462])
tensor([-1.3683])
tensor([0.3375])
tensor([1.0111])
tensor([-1.4352])
tensor([0.9774])


In [3]:
with open("piplist.txt","r") as f:
    for line in f:
        if "torch" in line:
            print(line)
            break

torch                     2.1.1



#### return = yield + break

In [6]:
def loader():
    with open("piplist.txt","r") as f:
        for line in f:
            yield line

for data in loader():
    print(data)
    if "torch" in data:
        print(data)
        break

Package                   Version

------------------------- ------------

anyio                     4.1.0

argon2-cffi               23.1.0

argon2-cffi-bindings      21.2.0

arrow                     1.3.0

asttokens                 2.4.1

async-lru                 2.0.4

attrs                     23.1.0

Babel                     2.13.1

beautifulsoup4            4.12.2

bleach                    6.1.0

certifi                   2023.11.17

cffi                      1.16.0

charset-normalizer        3.3.2

colorama                  0.4.6

comm                      0.2.0

contourpy                 1.2.0

cycler                    0.12.1

debugpy                   1.8.0

decorator                 5.1.1

defusedxml                0.7.1

exceptiongroup            1.2.0

executing                 2.0.1

fastjsonschema            2.19.0

filelock                  3.13.1

fonttools                 4.46.0

fqdn                      1.5.1

fsspec                    2023.12.1

gitdb          

In [7]:
ITER = iter(loader())

In [13]:
next(ITER)

'arrow                     1.3.0\n'

In [16]:
def mydecolator(func):
    print("aa")
    def wrapper():
        print("start")
        func()
        print("end")
    return wrapper

@mydecolator
def hello():
    print("hello")

print("here")
hello()

aa
here
start
hello
end


In [33]:
def mydecolator2(func):
    def wrapped_func(x):
        func(x+1)
    return wrapped_func

@mydecolator2
def hello(x):
    print(x)

hello(1)

2


In [34]:
hello

<function __main__.mydecolator2.<locals>.wrapped_func(x)>

In [39]:
help(hello)

Help on function wrapped_func in module __main__:

wrapped_func(x)



In [48]:
def mydecolater(func):
    import functools
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        print("Funcname:", func.__name__)        #=> 関数名
        print("Arguments:", args)                #=> 引数
        print("Keywords:", kwargs)               #=> キーワード
        ret = func(*args, **kwargs)
        print("Return:", ret)                    #=> 戻り値
        return ret
    return wrapper

@mydecolater
def func(msg1, msg2, flag=1, mode=2):
    """A sample function"""
    print("----", msg1, msg2, "----")
    return 1234
                  #=> A sample function

In [55]:
n=func("Hello", "Hello2", flag=1)
n

Funcname: func
Arguments: ('Hello', 'Hello2')
Keywords: {'flag': 1}
---- Hello Hello2 ----
Return: 1234


1234

In [50]:
print(n)                               #=> 1234
print(repr(func))                      #=> <function func at 0x7f693aa0b158>
print(func.__doc__)  

1234
<function mydecolater.<locals>.wrapper at 0x7f9018325090>
None


In [61]:
@mydecolater
def hello_add(x,y):
    print("hello")
    return x+y

n = hello_add(1,2)

Funcname: hello_add
Arguments: (1, 2)
Keywords: {}
hello
Return: 3


In [63]:
help(hello_add)

Help on function wrapper in module __main__:

wrapper(*args, **kwargs)
    # import functools
    # @functools.wraps(func)



In [66]:
func("hello","hello2",flag=1)

Funcname: func
Arguments: ('hello', 'hello2')
Keywords: {'flag': 1}
---- hello hello2 ----
Return: 1234


1234

In [75]:
def repeater(func):
    def wrapper():
        for i in range(10):
            func()
    return wrapper

@repeater
def hello():
    print("hello")

hello()

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello


In [80]:
def repeat_10(func):
    def wrapper(*args, **kwargs):
        for i in range(10):
            func(*args, **kwargs)
    return wrapper

@repeat_10
def hello(x,y):
    # print("hello")
    print("x+y:",x+y)

hello(1,2)

x+y: 3
x+y: 3
x+y: 3
x+y: 3
x+y: 3
x+y: 3
x+y: 3
x+y: 3
x+y: 3
x+y: 3


In [92]:
import torch
@repeat_10
def get_randn(seed=-1):
    if seed != -1:
        torch.manual_seed(seed)

    number = torch.randn(1).item()
    print(number)

get_randn(1)

0.6613521575927734
0.6613521575927734
0.6613521575927734
0.6613521575927734
0.6613521575927734
0.6613521575927734
0.6613521575927734
0.6613521575927734
0.6613521575927734
0.6613521575927734


@staticmethod なしでも問題なく動く、、、必要性が謎。

In [53]:
class MyClass():
    def __init__(self):
        ...

    @staticmethod
    def add(x,y):
        return x+y

MyClass.add(1,2)


3

@classmethod クラス自身を呼べる。どう使う？

In [54]:
class MyClass:
    def __init__(self):
        for i in range(10):
            print(i)
        self.aaa = 1
    @classmethod
    def my_class_method(cls):
        print(f"This is a class method of {cls}.")

MyClass.my_class_method()

This is a class method of <class '__main__.MyClass'>.


@properti, @x.setter は明示的に値の変更部分を作れて安全というメリットはありそう。

でもぶっちゃけmy_object._x を直接いじるのでいい気もする、、、。

In [31]:
class MyClass:
    def __init__(self, x):
        self._x = x

    @property
    def x(self):
        return self._x

    @x.setter
    def x(self, value):
        self._x = value

my_object = MyClass(10)
print(my_object.x)  # Output: 10
my_object.x = 20
print(my_object.x)  # Output: 20


10
20


In [21]:
my_object.x = 10
my_object._x

20

In [11]:
my_object = MyClass(10)
my_object.x

<bound method MyClass.x of <__main__.MyClass object at 0x7f62e02440d0>>

In [12]:
my_object._x

10

@abstractmethod を加えると、実装されていない場合に子クラスでエラーを起こしてくれる。

In [28]:
from abc import ABC, abstractmethod

class MyAbstractClass(ABC):
    # @abstractmethod
    def my_abstract_method(self):
        pass

class MyClass(MyAbstractClass):
    # def my_abstract_method(self):
    #     print("This is my implementation of the abstract method.")
    ...

my_object = MyClass()
my_object.my_abstract_method()


In [39]:
from functools import wraps

def my_decorator(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print("Before the function is called.")
        result = func(*args, **kwargs)
        print("After the function is called.")
        return result
    return wrapper

@my_decorator
def my_function():
    print("This is my function.")

# @wraps を入れないと以下が関数本体ではなく、wrapperになる。
my_function()
print(my_function.__name__)
print(help(my_function))

Before the function is called.
This is my function.
After the function is called.
my_function
Help on function my_function in module __main__:

my_function()

None


## クラス

In [40]:
class MyClass:
    """A simple example class"""         # 三重クォートによるコメント

    def __init__(self):                  # コンストラクタ
        self.name = ""

    def getName(self):                   # getName()メソッド
        return self.name

    def setName(self, name):             # setName()メソッド
        self.name = name

a = MyClass()                            # クラスのインスタンスを生成
a.setName("Tanaka")                      # setName()メソッドをコール
print(a.getName())                       # getName()メソッドをコール

Tanaka


In [42]:
help(MyClass)

Help on class MyClass in module __main__:

class MyClass(builtins.object)
 |  A simple example class
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  getName(self)
 |  
 |  setName(self, name)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [43]:
class MyClass:
    def __init__(self):
        self.name = ""              # インスタンス変数

a1 = MyClass()
a1.name = "Tanaka"

a2 = MyClass()
a2.name = "Suzuki"

print(a1.name)                       #=> Tanaka
print(a2.name)                       #=> Suzuki

Tanaka
Suzuki


In [49]:
class MyClass:
    PI = 3.14                        #=> クラス変数
    def __init__(self):
        ...
    def func():
        print("aaa")

print(MyClass.PI)                    #=> 3.14

3.14


In [50]:
MyClass.func()

aaa


In [57]:
class MyClass:
    count = 0                       # クラス変数を初期化

    def __init__(self):
        MyClass.count += 1          # クラス変数をカウントアップ

print(MyClass.count)                #=> 2
a1 = MyClass()
print(MyClass.count)                #=> 2
a2 = MyClass()
print(MyClass.count)                #=> 2

0
1
2


In [61]:
class MyClass:
    pass

a1 = MyClass()
a1.name2 = "Tanaka"                 # インスタンス変数の追加
MyClass.PI2 = 3.141593              # クラス変数の追加

In [62]:
a1.name2

'Tanaka'

In [64]:
MyClass.PI2

3.141593

In [59]:
class MyClass:
    PI = 3.14

a1 = MyClass()
a2 = MyClass()
print(a1.PI)                        # クラス変数 MyClass.PI(3.14) が参照される
a1.PI = 3.141593                    # インスタンス変数 a1.PI が生成される
print(a1.PI)                        # インスタンス変数 a1.PI(3.141593)が参照される
print(a2.PI)                        # クラス変数 MyClass.PI(3.14) が参照される

3.14
3.141593
3.14


In [65]:
class MyClass:
    PI = 3.14

a1 = MyClass()
a2 = MyClass()

In [69]:
a1.PI = 3.1415
a1.PI

3.1415

In [70]:
MyClass.PI

3.14

In [71]:
class MyClass:
    name = ""
    def setName(self, name):     # 第一引数は自インスタンス(self)
        self.name = name

a = MyClass()
a.setName("Tanaka")

In [73]:
class MyClass():
    def __init__(self, name):
        self.name = name
    def getName(self):
        return self.name

a = MyClass("Tanaka")
print(a.getName())                     #=> Tanaka

Tanaka


In [75]:
class MyClass:
    def hello(self):
        print("Hello")

class MyClass2(MyClass):
    def world(self):
        print("World")

a = MyClass2()
a.hello()                   #=> Hello
a.world()                   #=> World

Hello
World


In [74]:
class MyClass:
    def hello(self):
        print("Hello")

class MyClass2(MyClass):
    def hello(self):        # 親クラスのhello()メソッドをオーバーライド
        print("HELLO")

a = MyClass2()
a.hello()                   #=> HELLO

HELLO


In [81]:
class Father():
    def __init__(self,name,year):
        self.name = name
        self.year = year

    def hello(self):
        print("Hello.")

class Child(Father):
    def hello(self):
        print("Hello!")
        

student1 = Child("Nadal","33")
student1.hello()

Hello!


In [82]:
student1.name

'Nadal'

In [102]:
class MyClass1(object):
    def __init__(self):
       self.val1 = 123
       print("myclass1")

    def hello(self):
        print("hello")

class MyClass2(MyClass1):
    def __init__(self):
        super(MyClass2,self).__init__()
        super(MyClass2,self).__init__()
        super(MyClass2,self).__init__()

        super(MyClass2,self).hello()
        super(MyClass2,self).hello()
        super(MyClass2,self).hello()

        self.val2 = 456

a = MyClass2()
print(a.val1)               #=> 123
print(a.val2)               #=> 456

myclass1
myclass1
myclass1
hello
hello
hello
123
456


In [98]:
class MyClassA:
    def funcA(self):
        print("MyClassA:funcA")

class MyClassB:
    def funcB(self):
        print("MyClassB:funcB")

class MyClassC(MyClassA, MyClassB):
    pass

a = MyClassC()
a.funcA()                    # MyClassA のメソッドも
a.funcB()                    # MyClassB のメソッドも使用できる

MyClassA:funcA
MyClassB:funcB


In [108]:
class Father:
    def make_garden(self):
        print("----------")
        print("----------")
        print("|||ooo|||")
        print("----------")
        print("----------")

class Mother:
    def cook(self):
        print("curry and rice")
        print("mabo-tofu")
        print("goya-champru")

class Child(Father,Mother):
    pass

child1 = Child()
child1.make_garden()
print("\n")
child1.cook()

----------
----------
|||ooo|||
----------
----------


curry and rice
mabo-tofu
goya-champru


In [109]:
help(Child)

Help on class Child in module __main__:

class Child(Father, Mother)
 |  Method resolution order:
 |      Child
 |      Father
 |      Mother
 |      builtins.object
 |  
 |  Methods inherited from Father:
 |  
 |  make_garden(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from Father:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from Mother:
 |  
 |  cook(self)



In [112]:
help(StopIteration)

Help on class StopIteration in module builtins:

class StopIteration(Exception)
 |  Signal the end from iterator.__next__().
 |  
 |  Method resolution order:
 |      StopIteration
 |      Exception
 |      BaseException
 |      object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  value
 |      generator return value
 |  
 |  ----------------------------------------------------------------------
 |  Static methods inherited from Exception:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from BaseException:
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |